global:
  namespace: naavre

  ingress:
    domain: example.org

  secrets:
    k8sSecretCreator:
      apiToken:
    keycloak:
      adminPassword:
      naavreClientSecret:
      users: []
      postgresql:
        password:
    vrepaas:
      vreapi:
        secretKey:
        auth:
          superuser:
            email: "admin@example.org"
            username: admin
            password:
          apiUser:
            username: user
            password:
            apiToken:
      vreapp:
        secretKey:
      postgresql:
        password:

  common:
    velero:
      podAnnotations:
        backup.velero.io/backup-volumes: pvc-volume,emptydir-volume

  externalServices:
    notebookSearch:
      apiEndpoint:
      apiToken:
    GitHubRepoNaaVRECells:
      url:
      token:

argoWorkflows:
  enabled: true
  ingress:
    basePath: /argowf

jupyterhub:
  enabled: true
  ingress:
    basePAth: /vl-openlab
  vlabSlug: openlab
  singleuser:
    image:
      name: qcdis/n-a-a-vre
      tag: v2.5.0
    extraEnv:
      BASE_IMAGE_TAGS_URL: "https://github.com/QCDIS/NaaVRE-flavors/releases/download/v0.20.2/base_image_tags.json"
      MODULE_MAPPING_URL: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json

k8sSecretCreator:
  enabled: true
  ingress:
    basePath: /k8s-secret-creator

keycloak:
  enabled: true
  ingress:
    basePath: /auth

vrepaas:
  enabled: true

  vreapi:
    image:
      tag: latest
    ingress:
      basePath: /vre-api

  vreapp:
    image:
      tag: latest
    ingress:
      basePath: /vreapp
