global:
  ingress:
    domain: example.org

  secrets:
    k8sSecretCreator:
      apiToken:
    keycloak:
      naavreClientSecret:

  common:
    velero:
      podAnnotations:
        backup.velero.io/backup-volumes: pvc-volume,emptydir-volume

k8sSecretCreator:
  enabled: true
  ingress:
    basePath: /k8s-secret-creator

keycloak:
  enabled: true
  ingress:
    basePath: /auth

