global:
  ingress:
    domain: example.org

  secrets:
    k8sSecretCreator:
      apiToken:
    keycloak:
      naavreClientSecret:
    vrepaas:
      apiToken:

  common:
    velero:
      podAnnotations:
        backup.velero.io/backup-volumes: pvc-volume,emptydir-volume

argoWorkflows:
  enabled: true
  ingress:
    basePath: /argowf
  # TODO:
  #   - Create secret `argo-sso` containing
  #     data:
  #       client-id: naavre
  #       client-secret: {{ .Values.global.secrets.keycloak.naavreClientSecret | default "" | b64enc }}
  #   - Create executor role
  #   - Propagate SA token

k8sSecretCreator:
  enabled: true
  ingress:
    basePath: /k8s-secret-creator

keycloak:
  enabled: true
  ingress:
    basePath: /auth

vrepaas:
  enabled: true

  vreapi:
    image:
      tag: latest
    ingress:
      basePath: /vre-api

  vreapp:
    image:
      tag: latest
    ingress:
      basePath: /vreapp
