global:
  namespace: naavre

  ingress:
    domain: example.com

  secrets:
    k8sSecretCreator:
      apiToken: <a random token>
    keycloak:
      adminPassword: <a random password>
      naavreClientSecret: <a random secret>
      # Adding users is optional. To not create any, remove the `users` entry.
      users:
        - username: my-user
          password: <a random password>
      postgresql:
        password: <a random password>
    vrepaas:
      vreapi:
        secretKey: <a random secret>
        auth:
          superuser:
            email: "admin@example.com"
            username: admin
            password: <a random password>
          apiUser:
            username: user
            password: <a random password>
            apiToken: <a random token>
      vreapp:
        secretKey: <a random secret>
      postgresql:
        password: <a random password>

  externalServices:
    notebookSearch:
      apiEndpoint: "<Notebook search API endpoint URL>"
      apiToken: <API token>
    GitHubRepoNaaVRECells:
      url: "<Repo created from template https://github.com/QCDIS/NaaVRE-cells>"
      token: "<Token generated following the instructions from the template>"

jupyterhub:
  ingress:
    basePath: /vl-openlab
  vlab:
    slug: openlab
    title: "NaaVRE Open Lab"
    description: "Open experimentation with virtual labs"