global:
  ingressDomain: naavre-dev.minikube.test

  common:
    velero:
      podAnnotations:
        backup.velero.io/backup-volumes: pvc-volume,emptydir-volume

  keycloak:
    adminUser: admin
    adminPassword: admin
    postgresql:
      postgresPassword: fake_postgres_password
      Password: fake_password
