global:
  ingress:
    domain: example.org

  secrets:
    keycloak:
      naavreClientSecret:

  common:
    velero:
      podAnnotations:
        backup.velero.io/backup-volumes: pvc-volume,emptydir-volume

keycloak:
  enabled: true
  ingress:
    basePath: /auth

