{{- if .Values.jupyterhub.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.jupyterhub.fullnameOverride }}-create-vl-in-paas"
  labels:
    {{- include "naavre.labels" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: "{{ .Values.jupyterhub.fullnameOverride }}-create-vl-in-paas"
      containers:
        - name: executor
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              POD_NAME=$(kubectl get pod -l app.kubernetes.io/name=vreapi -o jsonpath='{.items[0].metadata.name}');
              echo "Waiting for pod $POD_NAME"
              kubectl wait --for=condition=ready pod $POD_NAME --timeout=300s || exit 1
              kubectl exec $POD_NAME -- /opt/venv/bin/python manage.py shell -c "from virtual_labs.models import VirtualLab; VirtualLab.objects.filter(slug='{{ .Values.jupyterhub.singleuser.extraEnv.VLAB_SLUG | default .Values.jupyterhub.fullnameOverride }}').exists() or VirtualLab.objects.create(title='{{ .Values.jupyterhub.singleuser.extraEnv.VLAB_TITLE | default .Values.jupyterhub.fullnameOverride }}', slug='{{ .Values.jupyterhub.singleuser.extraEnv.VLAB_SLUG | default .Values.jupyterhub.fullnameOverride }}', description='{{ .Values.jupyterhub.singleuser.extraEnv.VLAB_DESCRIPTION | default .Values.jupyterhub.fullnameOverride }}', base_url='{{ .Values.jupyterhub.hub.baseUrl }}', fqdn='{{ index .Values.jupyterhub.ingress.hosts 0 }}', ingress_ssl_port='443' , image_name='{{ .Values.jupyterhub.singleuser.image.name }}', image_tag='{{ .Values.jupyterhub.singleuser.image.tag }}')"
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.jupyterhub.fullnameOverride }}-create-vl-in-paas"
  labels:
    {{- include "naavre.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.jupyterhub.fullnameOverride }}-create-vl-in-paas"
  labels:
    {{- include "naavre.labels" . | nindent 4 }}
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['list', 'get', 'watch']
  - apiGroups: ['']
    resources: ['pods/exec']
    verbs: ['create']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.jupyterhub.fullnameOverride }}-create-vl-in-paas"
  labels:
    {{- include "naavre.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.jupyterhub.fullnameOverride }}-create-vl-in-paas"
roleRef:
  kind: Role
  name: "{{ .Values.jupyterhub.fullnameOverride }}-create-vl-in-paas"
  apiGroup: rbac.authorization.k8s.io
{{- end }}