{{- if index .Values "argo-workflows" "enabled" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "argo-sso"
  labels:
    {{- include "naavre.labels" . | nindent 4 }}
data:
  client-id: {{ .Values.global.secrets.keycloak.client_id | default "" | b64enc }}
  client-secret: {{ .Values.global.secrets.keycloak.client_secret | default "" | b64enc }}
{{- end }}