{{- if index .Values "argo-workflows" "enabled" }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-vreapi
rules:
  - verbs:
      - get
      - watch
      - patch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
  - verbs:
      - list
      - watch
      - create
      - get
      - update
      - delete
    apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
      - workflowartifactgctasks
      - workflowtemplates
      - workflows
  - verbs:
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
      - workflowartifactgctasks/status
      - workflows/status
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-vreapi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-vreapi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-vreapi
subjects:
- kind: ServiceAccount
  name: argo-vreapi
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-vreapi.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-vreapi
type: kubernetes.io/service-account-token
{{- end }}