argo-workflows:
  enabled: true

jupyterhub:
  enabled: true

k8s-secret-creator:
  enabled: true

keycloak:
  enabled: true

vrepaas:
  enabled: true

global:
  secrets:
    keycloak:
      client_id:
      client_secret:
